### ISSUE TITLE
您的粗校正工具很棒，有没有计划做基于特征提取与匹配的精细配准校正

### ISSUE THREAD

**Issue by 18702738101** [ytkz11/AerialPictureCorrection#1]

**Comment by ytkz11** [comment]
持续更新，下一步计划就是特征提取与匹配

**Comment by andynnnnn** [comment]
您好，我从您的粗校正工具中获益匪浅，想咨询下您。我看您的代码中仅对Yaw偏航角进行校正，效果也非常好。有无尝试针对Pitch、Roll和Yaw进行综合校正呢？我现在困惑于此。非常想和您构建联系~~谢谢您
